# apiVersion: v1
# kind: Service
# metadata:
# name: flask-app
# name: flask-app
# spec:
#   selector:
#     app: flask-app
#   ports:
#   - name: http
#     port: 80
#     targetPort: 5000
#     nodeport: 32000

apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  selector:
    app: flask-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: NodePort
